### ISSUE TITLE
github URL is wrong in package.json

### ISSUE THREAD

**Issue by amcghie** [shahata/jsdelivr-cdn-data#10]
The `repository.url` field in `package.json` is invalid, this is causing my `npm install` to hang and eventually fail with the following error:
```
verbose node v11.3.0
verbose npm  v6.4.1
error Error while executing:
error /usr/bin/git ls-remote -h -t git://github.com/shahata/jsdelivr-cdn-data.git
error
error undefined
error exited with error code: 128
```

**Comment by kaskelotti** [comment]
What is the status of this issue? There's a PR that passes all checks. Is there something still blocking the merge?

**Comment by amcghie** [comment]
Nothing as far as I know. I'm waiting on @shahata (or another a maintainer) to merge

**Comment by shahata** [comment]
published. thanks.

**Comment by amcghie** [comment]
No worries. Thanks for a super useful library
